### ISSUE TITLE
Add an optional `step` column in the configuration spreadsheet

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/rate-my-recipe#23]
When you have 1000g of potatoes you could expect the "+" button to add at least 100g. Not 1g

Proposal: 

- In configuration add a column step to indicate the step applied by +/- buttons (in grammes)
- In the UI if the default is greater  or equal to 1000 display it as kg

**Comment by stephanegigandet** [comment]
Good idea.

**Comment by stephanegigandet** [comment]
Done by @alexfauquette in #25 , closing.
