### ISSUE TITLE
Internationalize the Rate my recipe project - Interface translation

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/rate-my-recipe#30]
The first instance of Rate my recipe is for a French project, Contribalim: https://contribalim.openfoodfacts.org
We need the interface to be translated in French.

**Comment by Sudhanva-Nadiger** [comment]
We need translation for only French & English? 
And also we are already using localisation thing in hunger-games project! We can make use of that ? 
Whats you suggest? @stephanegigandet

**Comment by stephanegigandet** [comment]
@Sudhanva-Nadiger that's right, @alexfauquette made a PR for that yesterday: https://github.com/openfoodfacts/rate-my-recipe/pull/31

**Comment by stephanegigandet** [comment]
We first need translation for French and English, but of course after we should be able to add translation for any language.
