### ISSUE TITLE
Create a “Share recipe” button to create POST request to recipe portal

### ISSUE THREAD

**Issue by GitPersSiham** [openfoodfacts/rate-my-recipe#8]

**Comment by alexfauquette** [comment]
Objecctif: Créer un bouton qui envoi une requête POST à une URL fictive `https://amathjourney.com/api/yololo` (celle là je suis sure que le proprio est respectable :) )


Ca doit contenir: les values et les quantités.


Pour récupérer les ingredients dans un coposant: https://github.com/openfoodfacts/rate-my-recipe/blob/7ba7097edcb597772afb4855e16da8cf2e788219/app/page.tsx#L36-L38

Pour les flatten: https://github.com/openfoodfacts/rate-my-recipe/blob/7ba7097edcb597772afb4855e16da8cf2e788219/redux/selectors.ts#L12-L29

Le boutin est être nimporte où pour l'instant
