### ISSUE TITLE
Show nutriscore numeric score in addition to nutriscore letter grade 

### ISSUE THREAD

**Issue by GitPersSiham** [openfoodfacts/rate-my-recipe#9]

**Comment by stephanegigandet** [comment]
The nutriscore numeric score is available in the nutriscore_score field:

https://world.openfoodfacts.org/api/v3/product/0033776112059?fields=nutriscore_grade,nutriscore_score

You can remove the &fields parameter in order to see all available fields for a product.

**Comment by alexfauquette** [comment]
Pour modifier la requete : https://github.com/openfoodfacts/rate-my-recipe/blob/58aec1acc50ba0b0750b978e92f7e8c8c3b3ca27/redux/reducers/recipes.ts/#L43-L59

Dan,s le même fichie rmodifier le reducer qui recupere le resultat

Pour l'affichage https://github.com/openfoodfacts/rate-my-recipe/blob/58aec1acc50ba0b0750b978e92f7e8c8c3b3ca27/components/ShowNutritionalTable.tsx/#L49-L52

**Comment by stephanegigandet** [comment]
This has been implemented already, closing.
